export const LabelNames = {
  //****************Menu & Common************************//

  all: 'all',
  lbl_login_user: 'login_user',
  lbl_schedules: 'schedules.title',
  getStarted: 'banner.getStarted',
  welcomeToAtedu: 'banner.welcomeToAtedu',
  bannerMessages: 'banner.messages',

  smenu_dashboard: 'dashboard.title',
  smenu_schedules: 'schedules.title',
  smenu_classes: 'classes.title',
  smenu_documents: 'documents',
  smenu_files: 'files',
  smenu_students: 'students.title',
  smenu_assignments: 'assignments',
  smenu_groups: 'groups',
  smenu_mail: 'mail.title',
  smenu_messages: 'messages',
  smenu_attendance: 'attendance',
  smenu_news: 'news.title',
  smenu_news_manage: 'news.manageNews',
  smenu_events: 'events.title',
  smenu_myprofile: 'myProfile',
  smenu_admin: 'administration.title',
  smenu_admin_useraccounts: 'administration.userAccounts',
  smenu_admin_classes: 'administration.classes',
  smenu_admin_activities: 'administration.activities',

  //***********************************Schedule page***********************************//
  btn_Print: 'schedules.print',
  schoolWeekView: 'schedules.schoolWeekView',
  weekView: 'schedules.weekView',
  dayView: 'schedules.dayView',
  monthView: 'schedules.monthView',
  mySchedules: 'schedules.mySchedules',
  schoolEvent: 'schedules.schoolEvent',
  classSchedule: 'schedules.classSchedule',
  privateEvent: 'schedules.privateEvent',
  examEvent: 'schedules.examEvent',
  eventFoundationDay: 'events.foundationDay',
  readChapter: 'schedules.readChapter',
  homeWorks: 'homeworks.title',
  //***********************************added for the meantime *****************//
  homeWorksAnswerWorkbook: 'homeworks.answerWorkbook',
  homeWorksReadPages: 'homeworks.readPages',
  homeWorksResearchWork: 'homeworks.researchWork',
  homeWorksReadingWork: 'homeworks.readingWork',
  //********************************************************************************//

  assignments: 'assignments',
  assignment: 'assignment.title',
  attendance: 'attendance',
  submitted: 'actions.submitted',
  edited: 'actions.edited',
  assignmentBookReport: 'assignment.bookReport',
  assignmentEquations: 'assignment.equations',
  assignmentPresentation: 'assignment.presentation',
  assignmentReactionPaper: 'assignment.reactionPaper',
  //***********************************Social ***********************************//

  writeComment: 'actions.writeComment',
  likes: 'social.likes',
  seeMore: 'social.seeMore',
  seeLess: 'social.seeLess',
  comment: 'social.comment',
  postedThis: 'social.postedThis',
  shared: 'social.shared',
  showMore: 'actions.showMore',
  more: 'actions.more',

  //***********************************Classes page***********************************//
  classes: 'classes.title',
  myNotes: 'classes.myNotes',
  teachersNote: 'classes.teachersNotes',
  toDo: 'classes.toDo',
  media: 'classes.media',
  quizzes: 'classes.quizzes',
  grades: 'classes.grades',
  addNote: 'actions.addNote',
  addNotes: 'actions.addNotes',
  mediaEnglishNotes: 'media.mediaEnglishNotes',
  //**********************************************************************************//
  dueSoon: 'dueSoon.title',
  dueToday: 'dueSoon.dueToday',
  dueTomorrow: 'dueSoon.dueTomorrow',
  dueAnswerWorkbook: 'dueSoon.answerWorkbook',
  dueReadPages: 'dueSoon.readPages',
  duePresentation: 'dueSoon.presentation',
  dueReadingMaterial: 'dueSoon.readingMaterial',

  dateCreated: 'datecreated',
  upload: 'upload',
  datecreated: 'datecreated',
  latestoldest: 'latestoldest',
  new: 'new',
  download: 'download',
  lesson: 'lesson',
  youWere: 'youWere',
  minsLate: 'minsLate',

  //***********************************Quizzes tab***********************************//
  recentscore: 'recentscore',
  almostperfect: 'almostperfect',
  goodjob: 'goodjob',
  needhelp: 'needhelp',
  keepitup: 'keepitup',
  yourseldomabsentnorlate: 'yourseldomabsentnorlate',
  lessonsAttended: 'lessonsAttended',
  absences: 'absences',

  averagescore: 'averagescore',
  title: 'title',
  score: 'score',
  quiz: 'quiz',
  uploadedby: 'uploadedby',

  //***********************************Grades tab***********************************//
  youreachamp: 'youreachamp',
  schoolyear: 'schoolyear',
  classicview: 'classicview',

  //***********************************Calendar Classes Right Layout*******************//
  today: 'today',
  mon: 'mon',
  tue: 'tue',
  wed: 'wed',
  thur: 'thu',
  fri: 'fri',

  //***********************************News page***********************************//
  news: 'news.title',
  schoolnews: 'news.schoolnews',
  events: 'news.events',
  miscellaneous: 'news.miscellaneous',
  nextpost: 'news.nextpost',
  previouspost: 'news.previouspost',
  carouselNewsTeachingStrategy: 'news.sampleNewsTeachingStrategy',
  carouselNewsDIY: 'news.sampleNewsDIY',
  carouselNewsHatAndFestive: 'news.sampleNewsHatAndFestive',
  carouselNewsBlackLives: 'news.sampleNewsBlackLives',
  announcementSchoolVacation: 'news.schoolVacationCalendar',
  schoolVacationCalendar: 'news.schoolVacationCalendar',
  newZealandSchool: 'news.newZealandSchool',
  schoolStart: 'news.schoolStart',
  autumnVacation: 'news.autumnVacation',
  christmasHoliday: 'news.christmasHoliday',
  winterVacation: 'news.winterVacation',
  easterVacation: 'news.easterVacation',
  allPrayerDay: 'news.allPrayerDay',
  ascensionDay: 'news.ascensionDay',
  whitMonday: 'news.whitMonday',
  constitutionDay: 'news.constitutionDay',
  lastDayOfTerm: 'news.lastDayOfTerm',
  firstDayOfTerm: 'news.firstDayOfTerm',
  weContinouslyUpdateSchoolCalendar: 'news.weContinouslyUpdateSchoolCalendar',
  onThisPageUpdateSchoolCalendar: 'news.onThisPageUpdateSchoolCalendar',
  youCanAlwaysContactUs: 'news.youCanAlwaysContactUs',
  relatedPosts: 'news.relatedPosts',
  categoryshoolnewdesc: 'news.categoryshoolnewdesc',
  categoryeventsdesc: 'news.categoryeventsdesc',
  categorymiscellaneousdesc: 'news.categorymiscellaneousdesc',
  categorymodaltitle: 'news.categorymodaltitle',
  categorymodaltitle1: 'news.categorymodaltitle1',
  continue: 'news.continue',
  previous: 'news.previous',
  finish: 'actions.finish',
  featuredthumbnail: 'news.featuredthumbnail',
  smallThumbnail: 'news.smallThumbnail',
  smallThumbnailDescription: 'news.smallThumbnailDescription',
  displaywhenyourstory: 'news.displaywhenyourstory',

  //***********************************Upload file***********************************//
  uploading: 'actions.uploading',
  uploadCompleted: 'actions.uploadCompleted',

  //***********************************Subjects***********************************//
  english: 'subjects.english',
  mathematics: 'subjects.mathematics',
  biology: 'subjects.biology',
  chemistry: 'subjects.chemistry',
  socialStudies: 'subjects.socialStudies',
  history: 'subjects.history',
  literature: 'subjects.literature',
  //***********************************Date picker translation***********************************//
  january: 'monthLongList.january',
  february: 'monthLongList.february',
  march: 'monthLongList.march',
  april: 'monthLongList.april',
  mayLong: 'monthLongList.may',
  june: 'monthLongList.june',
  july: 'monthLongList.july',
  august: 'monthLongList.august',
  september: 'monthLongList.september',
  october: 'monthLongList.october',
  november: 'monthLongList.november',
  december: 'monthLongList.december',

  jan: 'monthShortList.jan',
  feb: 'monthShortList.feb',
  mar: 'monthShortList.mar',
  apr: 'monthShortList.apr',
  mayShort: 'monthShortList.may',
  jun: 'monthShortList.jun',
  jul: 'monthShortList.jul',
  aug: 'monthShortList.aug',
  sep: 'monthShortList.sep',
  oct: 'monthShortList.oct',
  nov: 'monthShortList.nov',
  dec: 'monthShortList.dec',

  monday: 'dayLongList.monday',
  tuesday: 'dayLongList.tuesday',
  wednesday: 'dayLongList.wednesday',
  thursday: 'dayLongList.thursday',
  friday: 'dayLongList.friday',
  saturday: 'dayLongList.saturday',
  sunday: 'dayLongList.sunday',

  mo: 'dayShortList.mo',
  tu: 'dayShortList.tu',
  we: 'dayShortList.we',
  th: 'dayShortList.th',
  fr: 'dayShortList.fr',
  sa: 'dayShortList.sa',
  su: 'dayShortList.su',

  gotoNextDay: 'gotoNextDay',
  gotoPreviousDay: 'gotoPreviousDay',
  gotoToday: 'goToToday',
  gotoNextWeek: 'gotoNextWeek',
  gotoPreviousWeek: 'gotoPreviousWeek',
  gotoPrevMonth: 'gotoPrevMonth',
  gotoNextMonth: 'gotoNextMonth',
  gotoPrevYear: 'gotoPrevYear',
  gotoNextYear: 'gotoNextYear',
  //***********************************User Profile***********************************//
  userProfile: 'userProfile',
  firstname: 'firstname',
  lastname: 'lastname',
  email: 'email',
  save: 'save',
  recordsaved: 'recordsaved',

  //***********************************Administrator*************************************/
  myquicklinks: 'myquicklinks',
  create: 'create',
  task: 'task',
  to: 'to',
  addtitle: 'addtitle',
  invitepeople: 'invitepeople',
  searchforroomorlocation: 'searchforroomorlocation',
  adddescription: 'adddescription',
  allday: 'allday',
  tomorrow: 'tomorrow',
  calendar: 'calendar',
  todo: 'todo',
  switchViews: 'switchViews',
  agenda: 'agenda',
  allTasks: 'allTasks',
  ateduTask: 'ateduTask',
  schoolTasks: 'schoolTasks',
  personalTasks: 'personalTasks',
  showRecentlyCompleted: 'showRecentlyCompleted',
  hideCompletedTasks: 'hideCompletedTasks',
  //*********************************News Story****************************************/
  createddate: 'createddate',
  lastmodifieddate: 'lastmodifieddate',
  category: 'category',
  privacy: 'privacy',
  publishon: 'publishon',
  archiveon: 'archiveon',
  customizedurl: 'customizedurl',
  featuredarticle: 'featuredarticle',
  saveasdraft: 'saveasdraft',
  publish: 'publish',
  now: 'now',
  never: 'never',
  //*********************************Teacher Dashboard****************************************/
  uploaddocument: 'uploaddocument',
  mytask: 'mytask',
  shareddocument: 'shareddocument',
  //*********************************Account Setting****************************************/
  accountsettings: 'accountsettings',
  //*********************************Account Setting Menu****************************************/
  profile: 'profile',
  security: 'security',
  notification: 'notification',
  language: 'language',
  yourpersonalaccount: 'yourpersonalaccount',
  updateprofile: 'updateprofile',
  updateprofiledesc: 'updateprofiledesc',
  uploadnewphoto: 'uploadnewphoto',
  contactno: 'contactno',
  secondarycontactno: 'secondarycontactno',
  emailaddress: 'emailaddress',
  typehere: 'typehere',
  guardiandetails: 'guardiandetails',
  addaguardian: 'addaguardian',
  removeasaguardian: 'removeasaguardian',
  fullname: 'fullname',
  relationship: 'relationship',
  schoolEmail: 'schoolEmail',
  //*********************************Notification Settings****************************************/
  notificationDesc: 'notificationSettings.description',
  aboutYourPost: 'notificationSettings.aboutYourPost',
  aboutYourPostDesc: 'notificationSettings.aboutYourPostDesc',
  sms: 'notificationSettings.sms',
  push: 'notificationSettings.push',
  // email:                                                  "notificationSettings.",
  inApp: 'notificationSettings.inApp',
  reminders: 'notificationSettings.reminders',
  remindersDesc: 'notificationSettings.remindersDesc',
  // "events":"notificationSettings.",
  eventsDesc: 'notificationSettings.eventsDesc',
  classUpdates: 'notificationSettings.classUpdates',
  classUpdatesDesc: 'notificationSettings.classUpdatesDesc',
  allhomeworks: 'allhomeworks',
  passdue: 'allhomeworks',
  az: 'az',
  za: 'za',
  allassignment: 'allassignment',
  date: 'date',
  oldestlatest: 'oldestlatest',
  update: 'update',
  //*********************************USER PROFILE****************************************/
  ateduAccount: 'ateduAccount',
  guardian: 'guardian',
  employmentInfo: 'employmentInfo',
  student: 'student',
  doYouWantToSaveThisUser: 'doYouWantToSaveThisUser',
  userprofileDesc: 'userprofileDesc',
  userAccounts: 'userAccounts',
  staff: 'staff',
  userprofilecreate: 'userprofilecreate',
  userprofilecreate1: 'userprofilecreate1',
  userprofileDesc1: 'userprofileDesc1',
  userprofileDesc2: 'userprofileDesc2',

  suggestedTags: 'suggestedTags',
  noRoleTagsFound: 'noRoleTagsFound',
  profiledesc: 'profiledesc',
  roles: 'roles',
  socialSecurityNo: 'socialSecurityNo',
  temporaryPassword: 'temporaryPassword',
  activateAccount: 'activateAccount',
  accountStatus: 'accountStatus',
  cancel: 'cancel',
  next: 'next',

  pleaseInputRequiredField: 'pleaseInputRequiredField',
  shouldOnlyContainNumber: 'shouldOnlyContainNumber',
  employementInformation: 'employementInformation',
  employeedesc: 'employeedesc',
  bankNo: 'bankNo',
  bankAccountNo: 'bankAccountNo',
  withdrawalPercentage: 'withdrawalPercentage',
  employmentRate: 'employmentRate',
  dateEmployment: 'dateEmployment',
  dateResignation: 'dateResignation',
  homeInstitutionNo: 'homeInstitutionNo',
  enter: 'enter',
  selectadate: 'selectadate',
};

export const Literal = {
  error: 'error',
  string: 'string',
  object_Object: '[object Object]',
  object_Array: '[object Array]',
  AUTH_STOREGE_KEY: 'atedusso.authentication',
};

export const HttpMethods = {
  CONNECT: 'CONNECT',
  DELETE: 'DELETE',
  GET: 'GET',
  HEAD: 'HEAD',
  OPTIONS: 'OPTIONS',
  PATCH: 'PATCH',
  POST: 'POST',
  PUT: 'PUT',
  TRACE: 'TRACE',
};

//export const AteduDataRequest = {

//};

//export const AteduDataResponse = {
//    boolean
//}

export const AteduDataLiterals = {
  HEADER_CHARACTER: '-',
  F_SLASH: '/',
  ARRAY_DELIMITER: ',',
  CHSK_WS_PING: 'chsk/ws-ping',
  STATUS_UPDATE: 'status/update',

  ID_MODIFIER: 'id/modifier',
  _META: '_meta',
  _VALIID_TIME: 'valid-time',
  _TX_TIME: 'tx-time',

  ENTITY_DATA: 'entity/data',
  ENTITY_DATA_FAIL: 'entity/data.fail',
  ENTITY_READ: 'entity/read',
  ENTITY_READ_FAIL: 'entity/read.fail',
  ENTITY_WRITE: 'entity/write',
  ENTITY_WRITE_FAIL: 'entity/write.fail',
  ENTITIES_AT: 'entities/at',

  SUBSCRIBE_IDS: 'subscribe/ids',
  SUBSCRIBE_IDS_FAIL: 'subscribe/ids.fail',

  USER_BY_EXTERNAL_ID: 'user/by-external-id',
  USER_FIRST_NAME: 'user/first-name',
  USER_LAST_NAME: 'user/last-name',
  USER_BIRTHDAY: "user/birthday",
  USER_CPRNUMBER: "user/cprnumber",
  USER_EMAIL: 'user/email',
  USER_ROLE: 'user/role',
  USER_DATA: 'user/data',
  USER_CONTACT: 'phone',
  USER_CONTACT1: 'phone1',
  USER_EXTERNAL_IDS: 'user/external-ids',
  USER_STATUS: 'user/status',

  ID_SCHOOL: 'id/school',
  HOME_CLASS_NAME: 'home-class/name',
  HOME_CLASS_CLASSES: 'home-class/classes',

  ID: 'id',
  SCHOOLS: 'schools',

  ERROR: 'error',
  ENTITY_ID: 'entity-id',

  STAFF_ROLES: 'staff/roles',
  STAFF_CLASSES: 'staff/classes',

  ROLE_F_SLASH: 'role/',
  ROLES: 'roles',

  STUDENT_BY_CLASS: 'students/by-class',
  ATTENDANCE_BY_LESSON: 'attendance/by-lesson',

  ID_CLASS: 'id/class',
  LESSON_DATA: 'lesson/data',
  LESSON_WEEK: 'lesson/week',
  STAFF_DATA: 'staff/data',
  ID_HOME_CLASS: 'id/home-class',
  ID_USER: 'id/user',
  STUDENT_CLASSES: 'student/classes',
  STUDENT_ROLES: 'student/roles',
  STUDENT_CLASS: 'student/classes',
  ATTENDANCE_CONFIRMED: 'lesson/attendance-confirmed',

  ABSENT_TYPE: 'absence/type',
  ATTENDANCE_DATA: 'attendance/data',
  ID_ATTENDANCE: 'id',
  ID_AUTHOR: 'id/author',
  ID_LESSON: 'id/lesson',
  ID_EVENT: 'id/event',
  ID_TARGET: 'id/target',
  ID_STUDENT: 'id/student',

  SUBJECT_NAME: 'subject/name',
  ID_FOR_SCHOOL: 'id/for-school',
  CLASS_DATA: 'class/data',
  NUMBER_OF_STUDENT: 'capacity',
  CLASS_NAME: 'class/name',
  XPRS_SUBJECT: 'id/subject-code',
  CLASS_YEAR_NUMBER: 'class/year-number',
  CLASS_ALIAS: 'alias',
  CLASS_START_DATE: 'start-date',
  CLASS_END_DATE: 'end-date'
};

export const Errors = {
  TIMED_OUT: 'TIMED_OUT',
  INVALID_USER: 'INVALID_USER',
  _FAIL: '.fail',
};

export const Roles = {
  ADMINISTRATOR: 'Administrator',
  STAFF: 'Staff',
  TEACHER: 'Teacher',
  SECURITY: 'Security',
  TENANT_ADMINISTRATOR: 'Tenant_Administrator',
  STUDENT: 'Student',
};
