import moment from 'moment';
import { intl } from '../commonFunction';
import { LabelNames } from '../constant';

let eventGuid = 0;
const May1 = moment('2021-05-01').format('YYYY-MM-DD');
const May2 = moment('2021-05-02').format('YYYY-MM-DD');
const May3 = moment('2021-05-03').format('YYYY-MM-DD');
const May4 = moment('2021-05-04').format('YYYY-MM-DD');
const May5 = moment('2021-05-05').format('YYYY-MM-DD');
const May8 = moment('2021-05-08').format('YYYY-MM-DD');
const May9 = moment('2021-05-09').format('YYYY-MM-DD');
const May10 = moment('2021-05-10').format('YYYY-MM-DD');
const May11 = moment('2021-05-11').format('YYYY-MM-DD');
const May12 = moment('2021-05-12').format('YYYY-MM-DD');
const May15 = moment('2021-05-15').format('YYYY-MM-DD');
const May16 = moment('2021-05-16').format('YYYY-MM-DD');
const May17 = moment('2021-05-17').format('YYYY-MM-DD');
const May18 = moment('2021-05-18').format('YYYY-MM-DD');
const May19 = moment('2021-05-19').format('YYYY-MM-DD');
const May22 = moment('2021-05-22').format('YYYY-MM-DD');
const May23 = moment('2021-05-23').format('YYYY-MM-DD');
const May24 = moment('2021-05-24').format('YYYY-MM-DD');
const May25 = moment('2021-05-25').format('YYYY-MM-DD');
const May26 = moment('2021-05-26').format('YYYY-MM-DD');
const May29 = moment('2021-05-29').format('YYYY-MM-DD');
const May30 = moment('2021-05-30').format('YYYY-MM-DD');
const May31 = moment('2021-05-31').format('YYYY-MM-DD');
const Jun1 = moment('2021-06-01').format('YYYY-MM-DD');
const Jun2 = moment('2021-06-02').format('YYYY-MM-DD');
const Jun5 = moment('2021-06-05').format('YYYY-MM-DD');
const Jun6 = moment('2021-06-06').format('YYYY-MM-DD');
const Jun7 = moment('2021-06-07').format('YYYY-MM-DD');
const Jun8 = moment('2021-06-08').format('YYYY-MM-DD');
const Jun9 = moment('2021-06-09').format('YYYY-MM-DD');

export const MONTH_EVENTS = [
  {
    id: createEventId(),
    title: intl(LabelNames.english),
    start: May1 + 'T08:00:00',
    end: May1 + 'T08:45:00',
    location: 'R.302',
    status: 1,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.mathematics),
    start: May1 + 'T09:00:00',
    end: May1 + 'T09:45:00',
    location: 'R.302',
    status: 2,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.english),
    start: May2 + 'T08:00:00',
    end: May2 + 'T08:45:00',
    location: 'R.302',
    status: 3,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.mathematics),
    start: May2 + 'T09:00:00',
    end: May2 + 'T09:45:00',
    location: 'R.302',
    status: 4,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: 'SC Meeting',
    start: May2 + 'T15:00:00',
    end: May2 + 'T15:30:00',
    location: 'Auditorium',
    status: 1,
    groupId: 'private',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.english),
    start: May3 + 'T08:00:00',
    end: May3 + 'T08:45:00',
    location: 'R.302',
    status: 1,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.mathematics),
    start: May3 + 'T09:00:00',
    end: May3 + 'T09:45:00',
    location: 'R.302',
    status: 1,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.english),
    start: May4 + 'T08:00:00',
    end: May4 + 'T08:45:00',
    location: 'R.302',
    status: 2,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.mathematics),
    start: May4 + 'T09:00:00',
    end: May4 + 'T09:45:00',
    location: 'R.302',
    status: 3,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: 'Exams',
    start: May4 + 'T14:00:00',
    end: May4 + 'T15:00:00',
    location: 'R.201',
    status: 1,
    groupId: 'exam',
  },
  {
    id: createEventId(),
    title: 'SC Meeting',
    start: May4 + 'T15:00:00',
    end: May4 + 'T15:30:00',
    location: 'Auditorium',
    status: 1,
    groupId: 'private',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.english),
    start: May5 + 'T08:00:00',
    end: May5 + 'T08:45:00',
    location: 'R.302',
    status: 4,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.mathematics),
    start: May5 + 'T09:00:00',
    end: May5 + 'T09:45:00',
    location: 'R.302',
    status: 1,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.english),
    start: May8 + 'T08:00:00',
    end: May8 + 'T08:45:00',
    location: 'R.302',
    status: 1,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.mathematics),
    start: May8 + 'T09:00:00',
    end: May8 + 'T09:45:00',
    location: 'R.302',
    status: 2,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.eventFoundationDay),
    start: May9,
    location: 'School',
    status: 1,
    groupId: 'schoolEvent',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.english),
    start: May9 + 'T08:00:00',
    end: May9 + 'T08:45:00',
    location: 'R.302',
    status: 3,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.mathematics),
    start: May9 + 'T09:00:00',
    end: May9 + 'T09:45:00',
    location: 'R.302',
    status: 4,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.english),
    start: May10 + 'T08:00:00',
    end: May10 + 'T08:45:00',
    location: 'R.302',
    status: 1,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.mathematics),
    start: May10 + 'T09:00:00',
    end: May10 + 'T09:45:00',
    location: 'R.302',
    status: 1,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: 'Football Practice',
    start: May10 + 'T10:00:00',
    end: May10 + 'T10:30:00',
    location: 'Field',
    status: 1,
    groupId: 'private',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.english),
    start: May11 + 'T08:00:00',
    end: May11 + 'T08:45:00',
    location: 'R.302',
    status: 2,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.mathematics),
    start: May11 + 'T09:00:00',
    end: May11 + 'T09:45:00',
    location: 'R.302',
    status: 3,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: 'Exams',
    start: May11 + 'T13:00:00',
    end: May11 + 'T13:45:00',
    location: 'R.201',
    status: 1,
    groupId: 'exam',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.english),
    start: May12 + 'T08:00:00',
    end: May12 + 'T08:45:00',
    location: 'R.302',
    status: 4,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.mathematics),
    start: May12 + 'T09:00:00',
    end: May12 + 'T09:45:00',
    location: 'R.302',
    status: 1,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.biology),
    start: May12 + 'T10:00:00',
    end: May12 + 'T11:00:00',
    location: 'LAB',
    status: 1,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.chemistry),
    start: May12 + 'T11:00:00',
    end: May12 + 'T12:00:00',
    location: 'LAB',
    status: 2,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.chemistry),
    start: May15 + 'T11:00:00',
    end: May15 + 'T12:00:00',
    location: 'LAB',
    status: 3,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.socialStudies),
    start: May15 + 'T13:00:00',
    end: May15 + 'T13:45:00',
    location: 'R.101',
    status: 4,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.english),
    start: May15 + 'T08:00:00',
    end: May15 + 'T08:45:00',
    location: 'R.302',
    status: 1,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.mathematics),
    start: May16 + 'T09:00:00',
    end: May16 + 'T09:45:00',
    location: 'R.302',
    status: 1,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.biology),
    start: May16 + 'T10:00:00',
    end: May16 + 'T11:00:00',
    location: 'LAB',
    status: 2,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.chemistry),
    start: May17 + 'T11:00:00',
    end: May17 + 'T12:00:00',
    location: 'LAB',
    status: 3,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.socialStudies),
    start: May17 + 'T13:00:00',
    end: May17 + 'T13:45:00',
    location: 'R.101',
    status: 4,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: 'Football Practice',
    start: May18 + 'T15:00:00',
    end: May18 + 'T15:30:00',
    location: 'Field',
    status: 1,
    groupId: 'private',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.english),
    start: May18 + 'T08:00:00',
    end: May18 + 'T08:45:00',
    location: 'R.302',
    status: 1,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.mathematics),
    start: May19 + 'T09:00:00',
    end: May19 + 'T09:45:00',
    location: 'R.302',
    status: 1,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.biology),
    start: May19 + 'T10:00:00',
    end: May19 + 'T11:00:00',
    location: 'LAB',
    status: 2,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.chemistry),
    start: May22 + 'T11:00:00',
    end: May22 + 'T12:00:00',
    location: 'LAB',
    status: 3,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.socialStudies),
    start: May22 + 'T13:00:00',
    end: May22 + 'T13:45:00',
    location: 'R.101',
    status: 4,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: 'SC Meeting',
    start: May23 + 'T15:00:00',
    end: May23 + 'T15:30:00',
    location: 'Auditorium',
    status: 1,
    groupId: 'private',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.mathematics),
    start: May23 + 'T09:00:00',
    end: May23 + 'T09:45:00',
    location: 'R.302',
    status: 1,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.english),
    start: May24 + 'T08:00:00',
    end: May24 + 'T08:45:00',
    location: 'R.302',
    status: 1,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.mathematics),
    start: May24 + 'T09:00:00',
    end: May24 + 'T09:45:00',
    location: 'R.302',
    status: 2,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.biology),
    start: May25 + 'T10:00:00',
    end: May25 + 'T11:00:00',
    location: 'LAB',
    status: 3,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.chemistry),
    start: May25 + 'T11:00:00',
    end: May25 + 'T12:00:00',
    location: 'LAB',
    status: 4,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.eventFoundationDay),
    start: May26,
    location: 'School',
    status: 1,
    groupId: 'schoolEvent',
  },
  {
    id: createEventId(),
    title: 'Lunch With Jens',
    start: May26 + 'T12:00:00',
    end: May26 + 'T12:30:00',
    location: 'Cafeteria',
    status: 1,
    groupId: 'private',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.socialStudies),
    start: May26 + 'T13:00:00',
    end: May26 + 'T13:45:00',
    location: 'R.101',
    status: 1,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: 'Exams',
    start: May29 + 'T14:00:00',
    end: May29 + 'T15:00:00',
    location: 'R.201',
    status: 1,
    groupId: 'exam',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.english),
    start: May29 + 'T08:00:00',
    end: May29 + 'T08:45:00',
    location: 'R.302',
    status: 1,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: 'Exams',
    start: May30 + 'T14:00:00',
    end: May30 + 'T15:00:00',
    location: 'R.201',
    status: 1,
    groupId: 'exam',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.biology),
    start: May30 + 'T10:00:00',
    end: May30 + 'T11:00:00',
    location: 'LAB',
    status: 2,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.english),
    start: May31 + 'T08:00:00',
    end: May31 + 'T08:45:00',
    location: 'R.302',
    status: 3,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.mathematics),
    start: May31 + 'T09:00:00',
    end: May31 + 'T09:45:00',
    location: 'R.302',
    status: 4,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.biology),
    start: May31 + 'T10:00:00',
    end: May31 + 'T11:00:00',
    location: 'LAB',
    status: 1,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.chemistry),
    start: May31 + 'T11:00:00',
    end: May31 + 'T12:00:00',
    location: 'LAB',
    status: 1,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: 'Lunch With Jens',
    start: May31 + 'T12:00:00',
    end: May31 + 'T12:30:00',
    location: 'Cafeteria',
    status: 1,
    groupId: 'private',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.socialStudies),
    start: May31 + 'T13:00:00',
    end: May31 + 'T13:45:00',
    location: 'R.101',
    status: 2,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: 'Exams',
    start: May31 + 'T14:00:00',
    end: May31 + 'T15:00:00',
    location: 'R.201',
    status: 1,
    groupId: 'exam',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.english),
    start: Jun1 + 'T08:00:00',
    end: Jun1 + 'T08:45:00',
    location: 'R.302',
    status: 3,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.mathematics),
    start: Jun1 + 'T09:00:00',
    end: Jun1 + 'T09:45:00',
    location: 'R.302',
    status: 4,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.biology),
    start: Jun1 + 'T10:00:00',
    end: Jun1 + 'T11:00:00',
    location: 'LAB',
    status: 1,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.chemistry),
    start: Jun1 + 'T11:00:00',
    end: Jun1 + 'T12:00:00',
    location: 'LAB',
    status: 1,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: 'Lunch With Jens',
    start: Jun2 + 'T12:00:00',
    end: Jun2 + 'T12:30:00',
    location: 'Cafeteria',
    status: 1,
    groupId: 'private',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.socialStudies),
    start: Jun2 + 'T13:00:00',
    end: Jun2 + 'T13:45:00',
    location: 'R.101',
    status: 2,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: 'Exams',
    start: Jun2 + 'T14:00:00',
    end: Jun2 + 'T15:00:00',
    location: 'R.201',
    status: 1,
    groupId: 'exam',
  },
  {
    id: createEventId(),
    title: 'SC Meeting',
    start: Jun2 + 'T15:00:00',
    end: Jun2 + 'T15:30:00',
    location: 'Auditorium',
    status: 1,
    groupId: 'private',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.eventFoundationDay),
    start: Jun5,
    location: 'School',
    status: 1,
    groupId: 'schoolEvent',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.biology),
    start: Jun5 + 'T10:00:00',
    end: Jun5 + 'T11:00:00',
    location: 'LAB A',
    status: 3,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.chemistry),
    start: Jun5 + 'T11:00:00',
    end: Jun5 + 'T12:00:00',
    location: 'LAB B',
    status: 4,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: 'Lunch With Jens',
    start: Jun5 + 'T12:00:00',
    end: Jun5 + 'T12:30:00',
    location: 'Cafeteria',
    status: 1,
    groupId: 'private',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.socialStudies),
    start: Jun5 + 'T13:00:00',
    end: Jun5 + 'T13:45:00',
    location: 'R.101',
    status: 1,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: 'SC Meeting',
    start: Jun5 + 'T15:00:00',
    end: Jun5 + 'T15:30:00',
    location: 'Auditorium',
    status: 1,
    groupId: 'private',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.english),
    start: Jun5 + 'T18:00:00',
    end: Jun5 + 'T18:45:00',
    location: 'R.302',
    status: 1,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.mathematics),
    start: Jun5 + 'T19:00:00',
    end: Jun5 + 'T19:45:00',
    location: 'R.302',
    status: 2,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: 'Football Practice',
    start: Jun5 + 'T20:00:00',
    end: Jun5 + 'T20:30:00',
    location: 'Field',
    status: 1,
    groupId: 'private',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.english),
    start: Jun6 + 'T08:00:00',
    end: Jun6 + 'T08:45:00',
    location: 'R.302',
    status: 3,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.mathematics),
    start: Jun6 + 'T09:00:00',
    end: Jun6 + 'T09:45:00',
    location: 'R.302',
    status: 4,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: 'SC Meeting',
    start: Jun6 + 'T15:00:00',
    end: Jun6 + 'T15:30:00',
    location: 'Auditorium',
    status: 1,
    groupId: 'private',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.english),
    start: Jun6 + 'T08:00:00',
    end: Jun6 + 'T08:45:00',
    location: 'R.302',
    status: 1,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.mathematics),
    start: Jun6 + 'T09:00:00',
    end: Jun6 + 'T09:45:00',
    location: 'R.302',
    status: 1,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: 'Exams',
    start: Jun6 + 'T18:00:00',
    end: Jun6 + 'T18:45:00',
    location: 'R.201',
    status: 1,
    groupId: 'exam',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.english),
    start: Jun7 + 'T08:00:00',
    end: Jun7 + 'T08:45:00',
    location: 'R.302',
    status: 2,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.mathematics),
    start: Jun7 + 'T09:00:00',
    end: Jun7 + 'T09:45:00',
    location: 'R.302',
    status: 3,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.english),
    start: Jun8 + 'T08:00:00',
    end: Jun8 + 'T08:45:00',
    location: 'R.302',
    status: 4,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.mathematics),
    start: Jun8 + 'T09:00:00',
    end: Jun8 + 'T09:45:00',
    location: 'R.302',
    status: 1,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.english),
    start: Jun8 + 'T08:00:00',
    end: Jun8 + 'T08:45:00',
    location: 'R.302',
    status: 1,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.mathematics),
    start: Jun8 + 'T09:00:00',
    end: Jun8 + 'T09:45:00',
    location: 'R.302',
    status: 2,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.english),
    start: Jun9 + 'T08:00:00',
    end: Jun9 + 'T08:45:00',
    location: 'R.302',
    status: 3,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.mathematics),
    start: Jun9 + 'T09:00:00',
    end: Jun9 + 'T09:45:00',
    location: 'R.302',
    status: 4,
    groupId: 'classSchedule',
  },
];

export function createEventId() {
  return String(eventGuid++);
}
