import moment from 'moment';
import { intl } from '../commonFunction';
import { LabelNames } from '../constant';

let eventGuid = 0;
const todayStr = moment().format('YYYY-MM-DD');
const minusOneDayStr = moment(todayStr)
  .subtract(1, 'days')
  .format('YYYY-MM-DD');
const minusTwoDayStr = moment(todayStr)
  .subtract(2, 'days')
  .format('YYYY-MM-DD');
const minusThreeDayStr = moment(todayStr)
  .subtract(3, 'days')
  .format('YYYY-MM-DD');
const plusOneDayStr = moment(todayStr).add(1, 'days').format('YYYY-MM-DD');

export const INITIAL_EVENTS = [
  {
    id: createEventId(),
    title: intl(LabelNames.english),
    start: minusThreeDayStr + 'T08:00:00',
    end: minusThreeDayStr + 'T08:45:00',
    location: 'R. 302 A',
    status: 1,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.mathematics),
    start: minusThreeDayStr + 'T09:00:00',
    end: minusThreeDayStr + 'T09:45:00',
    location: 'R. 302 B',
    status: 2,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.biology),
    start: minusThreeDayStr + 'T10:00:00',
    end: minusThreeDayStr + 'T11:00:00',
    location: 'LAB A',
    status: 3,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.chemistry),
    start: minusThreeDayStr + 'T11:00:00',
    end: minusThreeDayStr + 'T12:00:00',
    location: 'LAB B',
    status: 4,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.socialStudies),
    start: minusThreeDayStr + 'T13:00:00',
    end: minusThreeDayStr + 'T13:45:00',
    location: 'R. 101 C',
    status: 1,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.english),
    start: minusTwoDayStr + 'T08:00:00',
    end: minusTwoDayStr + 'T08:45:00',
    location: 'R. 302 A',
    status: 2,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.mathematics),
    start: minusTwoDayStr + 'T09:00:00',
    end: minusTwoDayStr + 'T09:45:00',
    location: 'R. 302 B',
    status: 3,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.biology),
    start: minusTwoDayStr + 'T10:00:00',
    end: minusTwoDayStr + 'T11:00:00',
    location: 'LAB A',
    status: 4,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.chemistry),
    start: minusTwoDayStr + 'T11:00:00',
    end: minusTwoDayStr + 'T12:00:00',
    location: 'LAB B',
    status: 1,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.socialStudies),
    start: minusTwoDayStr + 'T13:00:00',
    end: minusTwoDayStr + 'T13:45:00',
    location: 'R. 101 C',
    status: 2,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: 'Football Practice',
    start: minusTwoDayStr + 'T15:00:00',
    end: minusTwoDayStr + 'T15:30:00',
    location: 'Footbal Field',
    status: 3,
    groupId: 'private',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.english),
    start: minusOneDayStr + 'T08:00:00',
    end: minusOneDayStr + 'T08:45:00',
    location: 'R. 302 A',
    status: 4,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.mathematics),
    start: minusOneDayStr + 'T09:00:00',
    end: minusOneDayStr + 'T09:45:00',
    location: 'R. 302 B',
    status: 1,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.biology),
    start: minusOneDayStr + 'T10:00:00',
    end: minusOneDayStr + 'T11:00:00',
    location: 'LAB A',
    status: 2,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.chemistry),
    start: minusOneDayStr + 'T11:00:00',
    end: minusOneDayStr + 'T12:00:00',
    location: 'LAB B',
    status: 3,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.socialStudies),
    start: minusOneDayStr + 'T13:00:00',
    end: minusOneDayStr + 'T13:45:00',
    location: 'R. 101 C',
    status: 4,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: 'SC Meeting',
    start: minusOneDayStr + 'T15:00:00',
    end: minusOneDayStr + 'T15:30:00',
    location: 'Auditorium',
    status: 1,
    groupId: 'private',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.eventFoundationDay),
    start: todayStr,
    status: 1,
    groupId: 'schoolEvent',
  },
  {
    id: createEventId(),
    title: 'physics-101.2021.01',
    start: todayStr + 'T08:00:00',
    end: todayStr + 'T08:45:00',
    location: 'R. 302 A',
    status: 2,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.mathematics),
    start: todayStr + 'T09:00:00',
    end: todayStr + 'T09:45:00',
    location: 'R. 302 B',
    status: 3,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.biology),
    start: todayStr + 'T10:00:00',
    end: todayStr + 'T11:00:00',
    location: 'LAB A',
    status: 4,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.chemistry),
    start: todayStr + 'T11:00:00',
    end: todayStr + 'T12:00:00',
    location: 'LAB B',
    status: 1,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: 'Lunch With Jens',
    start: todayStr + 'T12:00:00',
    end: todayStr + 'T12:30:00',
    location: 'Cafeteria',
    status: 1,
    groupId: 'private',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.socialStudies),
    start: todayStr + 'T13:00:00',
    end: todayStr + 'T13:45:00',
    location: 'R. 101 C',
    status: 1,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: 'Exams',
    start: todayStr + 'T20:00:00',
    end: todayStr + 'T21:00:00',
    location: 'R. 201 A',
    status: 1,
    groupId: 'exam',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.english),
    start: plusOneDayStr + 'T08:00:00',
    end: plusOneDayStr + 'T08:45:00',
    location: 'R. 302 A',
    status: 1,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: 'Exams',
    start: plusOneDayStr + 'T09:00:00',
    end: plusOneDayStr + 'T09:45:00',
    location: 'R. 201 A',
    status: 1,
    groupId: 'exam',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.biology),
    start: plusOneDayStr + 'T10:00:00',
    end: plusOneDayStr + 'T11:00:00',
    location: 'LAB A',
    status: 1,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.chemistry),
    start: plusOneDayStr + 'T11:00:00',
    end: plusOneDayStr + 'T12:00:00',
    location: 'LAB B',
    status: 1,
    groupId: 'classSchedule',
  },
  {
    id: createEventId(),
    title: intl(LabelNames.socialStudies),
    start: plusOneDayStr + 'T13:00:00',
    end: plusOneDayStr + 'T13:45:00',
    location: 'R. 101 C',
    status: 1,
    groupId: 'classSchedule',
  },
];

export function createEventId() {
  return String(eventGuid++);
}
