import { ClassesState } from '../../types/store/classes';
import { intl } from '../../util/commonFunction';
import { LabelNames } from '../../util/constant';

export const classesInitialState: ClassesState = {
  classesInfo: {
    selectedClass: intl(LabelNames.english),
    selectedDate: new Date(),
    selectedDay: null,
    selectedTime: null,
    selectedLocation: null,
    selectedLate: null,
    bolSelected: false,
    selectedTab: '1',
    week: null,
    start: null,
    end: null,
    confirmed: false,
    selectedLesson: [],
    // selectedLesson:{
    //   lessonId: 0,
    //   isConfirmed: false
    // }
  },
  mediaList: [
    {
      name: intl(LabelNames.dueReadingMaterial),
      item: intl(LabelNames.literature),
      index: 1,
      isScrolling: true,
      icon: 'docx',
      selected: true,
      createdby: 'Mona Kane',
      lastupdated: 'Mon at 3:58 PM',
      fonticon: '',
      check: false,
    },
    {
      name: intl(LabelNames.mediaEnglishNotes),
      item: intl(LabelNames.mathematics),
      index: 2,
      isScrolling: true,
      icon: 'docx',
      selected: false,
      createdby: 'Mona Kane',
      lastupdated: 'Mon at 3:58 PM',
      fonticon: '',
      check: false,
    },
    {
      name: intl(LabelNames.lesson) + '-Oct2',
      item: intl(LabelNames.history),
      index: 3,
      isScrolling: false,
      icon: 'pptx',
      selected: false,
      createdby: 'Mona Kane',
      lastupdated: 'Mon at 3:58 PM',
      fonticon: '',
      check: false,
    },
    {
      name: intl(LabelNames.smenu_schedules),
      item: intl(LabelNames.history),
      index: 4,
      isScrolling: false,
      icon: 'docx',
      selected: false,
      createdby: 'Mona Kane',
      lastupdated: 'Mon at 3:58 PM',
      fonticon: '',
      check: false,
    },
  ],
  classesassignmentlist: [
    {
      name: intl(LabelNames.assignmentBookReport),
      item: intl(LabelNames.literature),
      index: 1,
      isScrolling: true,
      icon: 'docx',
      selected: false,
      createdby: 'Mona Kane',
      lastupdated: 'Mon at 3:58 PM',
      fonticon: '',
      uploaded: true,
    },
    {
      name: intl(LabelNames.assignmentEquations),
      item: intl(LabelNames.mathematics),
      index: 2,
      isScrolling: true,
      icon: 'xls',
      selected: false,
      createdby: 'Mona Kane',
      lastupdated: 'Mon at 3:58 PM',
      fonticon: '',
      uploaded: false,
    },
    {
      name: intl(LabelNames.assignmentPresentation),
      item: intl(LabelNames.history),
      index: 3,
      isScrolling: false,
      icon: 'pptx',
      selected: false,
      createdby: 'Mona Kane',
      lastupdated: 'Mon at 3:58 PM',
      fonticon: '',
      uploaded: false,
    },
    {
      name: intl(LabelNames.assignmentReactionPaper),
      item: intl(LabelNames.english),
      index: 4,
      isScrolling: false,
      icon: 'pptx',
      selected: false,
      createdby: 'Mona Kane',
      lastupdated: 'Mon at 3:58 PM',
      fonticon: '',
      uploaded: false,
    },
  ],
  classeshomeworklist: [
    {
      name: intl(LabelNames.homeWorksAnswerWorkbook) + ' (pages 18-20)',
      item: intl(LabelNames.mathematics),
      index: 1,
      isScrolling: true,
      icon: '',
      selected: false,
      createdby: 'Mona Kane',
      lastupdated: 'Mon at 3:58 PM',
      fonticon: 'PenWorkspace',
      uploaded: true,
    },
    {
      name: intl(LabelNames.homeWorksReadPages) + ' 65-70',
      item: intl(LabelNames.biology),
      index: 2,
      isScrolling: true,
      icon: '',
      selected: false,
      createdby: 'Mona Kane',
      lastupdated: 'Mon at 3:58 PM',
      fonticon: 'ReadingMode',
      uploaded: true,
    },
    {
      name: intl(LabelNames.homeWorksResearchWork),
      item: intl(LabelNames.history),
      index: 3,
      isScrolling: false,
      icon: '',
      selected: false,
      createdby: 'Mona Kane',
      lastupdated: 'Mon at 3:58 PM',
      fonticon: 'SearchIssue',
      uploaded: true,
    },
    {
      name: intl(LabelNames.homeWorksReadingWork),
      item: intl(LabelNames.english),
      index: 4,
      isScrolling: false,
      icon: '',
      selected: false,
      createdby: 'Mona Kane',
      lastupdated: 'Mon at 3:58 PM',
      fonticon: 'ReadingMode',
      uploaded: true,
    },
  ],
  scheduleInfo: [],
};
