import { DashboardState } from '../../types/store/dashboard';
import { intl } from '../../util/commonFunction';
import { LabelNames } from '../../util/constant';

export const dashboardInitialState: DashboardState = {
  assignmentlist: [
    {
      name: 'Book Report',
      item: 'Literature',
      index: 1,
      isScrolling: true,
      icon: 'docx',
      selected: true,
      createdby: 'Mona Kane',
      lastupdated: 'Mon at 3:58 PM',
      fonticon: '',
      date: 'Oct 2',
    },
    {
      name: 'Equation',
      item: 'Math',
      index: 2,
      isScrolling: true,
      icon: 'xlsx',
      selected: false,
      createdby: 'Mona Kane',
      lastupdated: 'Mon at 3:58 PM',
      fonticon: '',
      date: 'Oct 2',
    },
    {
      name: 'Presentation',
      item: 'History',
      index: 3,
      isScrolling: false,
      icon: 'pptx',
      selected: false,
      createdby: 'Mona Kane',
      lastupdated: 'Mon at 3:58 PM',
      fonticon: '',
      date: 'Oct 2',
    },
    {
      name: 'Reading Papers',
      item: 'English',
      index: 4,
      isScrolling: false,
      icon: 'pptx',
      selected: false,
      createdby: 'Mona Kane',
      lastupdated: 'Mon at 3:58 PM',
      fonticon: '',
      date: 'Oct 2',
    },
  ],
  homeworklist: [
    {
      name: intl(LabelNames.homeWorksAnswerWorkbook) + ' (pages 18-20)',
      item: intl(LabelNames.mathematics),
      index: 1,
      isScrolling: true,
      icon: '',
      selected: true,
      createdby: 'Mona Kane',
      lastupdated: 'Mon at 3:58 PM',
      fonticon: 'PenWorkspace',
      date: 'Oct 2',
    },
    {
      name: intl(LabelNames.homeWorksReadPages) + ' 65-70',
      item: intl(LabelNames.biology),
      index: 2,
      isScrolling: true,
      icon: '',
      selected: false,
      createdby: 'Mona Kane',
      lastupdated: 'Mon at 3:58 PM',
      fonticon: 'ReadingMode',
      date: 'Oct 2',
    },
    {
      name: intl(LabelNames.homeWorksResearchWork),
      item: intl(LabelNames.history),
      index: 3,
      isScrolling: false,
      icon: '',
      selected: false,
      createdby: 'Mona Kane',
      lastupdated: 'Mon at 3:58 PM',
      fonticon: 'SearchIssue',
      date: 'Oct 2',
    },
    {
      name: intl(LabelNames.homeWorksReadingWork),
      item: intl(LabelNames.english),
      index: 4,
      isScrolling: false,
      icon: '',
      selected: false,
      createdby: 'Mona Kane',
      lastupdated: 'Mon at 3:58 PM',
      fonticon: 'ReadingMode',
      date: 'Oct 2',
    },
  ],
  documentslist: [
    {
      name: 'Introduction',
      item: 'Literature',
      index: 1,
      isScrolling: true,
      icon: 'docx',
      selected: true,
      createdby: 'Mona Kane',
      lastupdated: 'Mon at 3:58 PM',
      fonticon: '',
      date: 'Oct 2',
    },
    {
      name: 'Module',
      item: 'Math',
      index: 2,
      isScrolling: true,
      icon: 'docx',
      selected: false,
      createdby: 'Mona Kane',
      lastupdated: 'Mon at 3:58 PM',
      fonticon: '',
      date: 'Oct 2',
    },
    {
      name: 'Reading Material',
      item: 'History',
      index: 3,
      isScrolling: false,
      icon: 'docx',
      selected: false,
      createdby: 'Mona Kane',
      lastupdated: 'Mon at 3:58 PM',
      fonticon: '',
      date: 'Oct 2',
    },
    {
      name: 'Lesson',
      item: 'English',
      index: 4,
      isScrolling: false,
      icon: 'docx',
      selected: false,
      createdby: 'Mona Kane',
      lastupdated: 'Mon at 3:58 PM',
      fonticon: '',
      date: 'Oct 2',
    },
  ],
  dueSoon: [
    {
      id: 1,
      dueDate: '8:00 AM',
      subject: 'Mathematics',
      description: 'Answer workbook',
      icon: 'PenWorkspace',
    },

    {
      id: 2,
      dueDate: '8:00 AM',
      subject: 'Biology',
      description: 'Read pages 60-70',
      icon: 'PenWorkspace',
    },

    {
      id: 3,
      dueDate: '8:00 AM',
      subject: 'Social Studies',
      description: 'Presentation',
      icon: 'PenWorkspace',
    },

    {
      id: 4,
      dueDate: '8:00 AM',
      subject: 'English',
      description: 'Reading material',
      icon: 'PenWorkspace',
    },

    {
      id: 5,
      dueDate: '8:00 AM',
      subject: 'Mathematics',
      description: 'Reading material',
      icon: 'PenWorkspace',
    },
  ],
};
