name: Merge Article Schedule
on:
  pull_request:
    types:
      - opened
      - edited
  schedule:
    # 9AM UTC
    - cron: 0 9 * * *
    
  workflow_dispatch:

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ATEDU_AUTOMATION_NONPROD }}
